### ISSUE TITLE
button-primary-active-fill 等 很多没有生成变量。

### ISSUE THREAD

**Issue by akai007** [mand-mobile/palette#6]

**Comment by xxyan0205** [comment]
目前还不支持2.x

**Comment by akai007** [comment]
@xxyan0205 好的，你知道要支持到2.x 需要注意哪些地方吗？

**Comment by xxyan0205** [comment]
> 你知道要支持到2.x 需要注意哪些地方吗

2.x跟1.x的stylus变量表存在很多不同，支持2.x需要单独引入相应stylus变量表，目前调速板内部的stylus变量表是写死的1.x的

**Comment by akai007** [comment]
> > 你知道要支持到2.x 需要注意哪些地方吗
> 
> 2.x跟1.x的stylus变量表存在很多不同，支持2.x需要单独引入相应stylus变量表，目前调色板内部的stylus变量表是写死的1.x的

嗯嗯，那目前我就以2.x 的位模板替换过去吧
